"""Pre-built scam call simulation scenarios.

Each scenario includes metadata, a full script (for transcript fallback),
and a reference to a pre-generated TTS audio file.  The audio files are
generated by ``scripts/generate_scenario_audio.py``.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

SCENARIOS_AUDIO_DIR = Path(__file__).resolve().parent.parent / "data" / "scenarios"


@dataclass
class ScenarioLine:
    speaker: str  # CALLER | VICTIM
    text: str
    time_offset: str  # display time e.g. "0:03"
    intent: str = "NORMAL"
    language: str = "hi"


@dataclass
class Scenario:
    id: str
    title: str
    description: str
    language: str
    duration_seconds: int
    expected_threat_score: float
    expected_intents: list[str] = field(default_factory=list)
    script: list[ScenarioLine] = field(default_factory=list)
    audio_filename: str | None = None

    @property
    def audio_path(self) -> Path | None:
        if self.audio_filename:
            p = SCENARIOS_AUDIO_DIR / self.audio_filename
            return p if p.exists() else None
        return None

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "title": self.title,
            "description": self.description,
            "language": self.language,
            "duration_seconds": self.duration_seconds,
            "expected_threat_score": self.expected_threat_score,
            "expected_intents": self.expected_intents,
            "has_audio": self.audio_path is not None,
            "script": [
                {
                    "speaker": l.speaker,
                    "text": l.text,
                    "time": l.time_offset,
                    "intent": l.intent,
                    "language": l.language,
                }
                for l in self.script
            ],
        }


# ---------------------------------------------------------------------------
# Built-in scenarios
# ---------------------------------------------------------------------------

SCENARIOS: list[Scenario] = [
    Scenario(
        id="cbi-hindi-1",
        title="CBI Digital Arrest (Hindi)",
        description="Caller impersonates a CBI officer, claims victim's Aadhaar is linked to money laundering, threatens arrest, demands immediate money transfer.",
        language="hi",
        duration_seconds=55,
        expected_threat_score=87,
        expected_intents=["IMPERSONATION", "LEGAL_THREAT", "MONEY_DEMAND", "INTIMIDATION"],
        audio_filename="cbi_hindi_1.mp3",
        script=[
            ScenarioLine("CALLER", "Namaste, main CBI Officer Rahul Kumar bol raha hoon. Aapka Aadhaar number money laundering case mein involved hai.", "0:03", "IMPERSONATION", "hi"),
            ScenarioLine("VICTIM", "Sorry? Main kuch samjha nahi...", "0:08", "NORMAL", "hi"),
            ScenarioLine("CALLER", "Aapko turant respond karna hoga! Supreme Court case number SC-2024-789 mein aapka naam hai. Agar abhi payment nahi ki toh arrest warrant issue ho jayega!", "0:15", "LEGAL_THREAT", "hi"),
            ScenarioLine("CALLER", "Aapke paas sirf 2 ghante hain. Rs 50,000 immediately transfer karo ya police aayegi!", "0:31", "MONEY_DEMAND", "hi"),
            ScenarioLine("VICTIM", "Main kya karun? Bahut dar lag raha hai...", "0:41", "NORMAL", "hi"),
            ScenarioLine("CALLER", "Bilkul mera hi follow karo. Kisi ko mat batao, warna aur serious charges honge!", "0:48", "INTIMIDATION", "hi"),
        ],
    ),
    Scenario(
        id="customs-english-1",
        title="Customs Parcel Scam (English)",
        description="Caller claims to be from Indian Customs, says a parcel with drugs was intercepted, threatens NCB investigation and passport cancellation.",
        language="en",
        duration_seconds=48,
        expected_threat_score=82,
        expected_intents=["IMPERSONATION", "LEGAL_THREAT", "INTIMIDATION"],
        audio_filename="customs_english_1.mp3",
        script=[
            ScenarioLine("CALLER", "Hello, this is the Indian Customs Department. Am I speaking with the account holder?", "0:03", "IMPERSONATION", "en"),
            ScenarioLine("VICTIM", "Yes, who is this?", "0:07", "NORMAL", "en"),
            ScenarioLine("CALLER", "A parcel addressed to your name has been intercepted at Mumbai International Airport. It contains illegal substances and counterfeit currency notes.", "0:12", "IMPERSONATION", "en"),
            ScenarioLine("CALLER", "The Narcotics Control Bureau has been notified. Your passport will be cancelled and a Red Corner Notice will be issued by Interpol.", "0:24", "LEGAL_THREAT", "en"),
            ScenarioLine("VICTIM", "But I haven't sent any parcel! There must be a mistake.", "0:32", "NORMAL", "en"),
            ScenarioLine("CALLER", "This is a very serious matter. Do not disconnect this call. Any attempt to contact others will be treated as evidence tampering and obstruction of justice.", "0:38", "INTIMIDATION", "en"),
        ],
    ),
    Scenario(
        id="bank-kyc-hindi-1",
        title="Bank KYC Fraud (Hindi)",
        description="Caller poses as bank representative, claims KYC has expired, threatens account blocking, asks for personal details and processing fee.",
        language="hi",
        duration_seconds=42,
        expected_threat_score=68,
        expected_intents=["IMPERSONATION", "URGENCY_CREATION", "IDENTITY_THEFT", "MONEY_DEMAND"],
        audio_filename="bank_kyc_hindi_1.mp3",
        script=[
            ScenarioLine("CALLER", "Namaste, main State Bank of India ka representative bol raha hoon. Kya main account holder se baat kar raha hoon?", "0:03", "IMPERSONATION", "hi"),
            ScenarioLine("VICTIM", "Haan, boliye.", "0:07", "NORMAL", "hi"),
            ScenarioLine("CALLER", "Sir aapka KYC expire ho gaya hai. 24 ghante mein aapka account permanently block ho jayega aur saara paisa freeze ho jayega.", "0:12", "URGENCY_CREATION", "hi"),
            ScenarioLine("CALLER", "KYC update karne ke liye mujhe aapka Aadhaar number aur account linked mobile ka OTP chahiye.", "0:22", "IDENTITY_THEFT", "hi"),
            ScenarioLine("VICTIM", "Lekin main branch mein jaake kar sakta hoon na?", "0:28", "NORMAL", "hi"),
            ScenarioLine("CALLER", "Nahi sir, online process hai. Aur 500 rupaye processing fee bhi lagegi jo UPI se turant transfer karni hogi.", "0:34", "MONEY_DEMAND", "hi"),
        ],
    ),
    Scenario(
        id="ed-english-1",
        title="ED Investigation Scam (English)",
        description="Caller impersonates Enforcement Directorate officer, claims victim's accounts are linked to a hawala network, demands penalty payment.",
        language="en",
        duration_seconds=50,
        expected_threat_score=85,
        expected_intents=["IMPERSONATION", "LEGAL_THREAT", "MONEY_DEMAND", "URGENCY_CREATION"],
        audio_filename="ed_english_1.mp3",
        script=[
            ScenarioLine("CALLER", "Good afternoon. This is Senior Investigation Officer from the Enforcement Directorate, Government of India.", "0:03", "IMPERSONATION", "en"),
            ScenarioLine("VICTIM", "Hello? What is this about?", "0:08", "NORMAL", "en"),
            ScenarioLine("CALLER", "Your bank accounts have been flagged in connection with a hawala money laundering network. Case reference ED-2026-4782.", "0:14", "LEGAL_THREAT", "en"),
            ScenarioLine("CALLER", "All your accounts will be frozen within the next one hour unless you pay the compliance penalty of 1 lakh rupees immediately.", "0:25", "MONEY_DEMAND", "en"),
            ScenarioLine("VICTIM", "This sounds suspicious. Can I verify with the ED office?", "0:33", "NORMAL", "en"),
            ScenarioLine("CALLER", "Do NOT contact anyone. This is a classified investigation. Any disclosure is punishable under the Prevention of Money Laundering Act with 7 years imprisonment.", "0:40", "INTIMIDATION", "en"),
        ],
    ),
    Scenario(
        id="trai-hindi-1",
        title="TRAI SIM Block Scam (Hindi)",
        description="Automated IVR-style call claiming TRAI will block the mobile number, connects to a fake cyber crime officer.",
        language="hi",
        duration_seconds=38,
        expected_threat_score=75,
        expected_intents=["IMPERSONATION", "LEGAL_THREAT", "URGENCY_CREATION"],
        audio_filename="trai_hindi_1.mp3",
        script=[
            ScenarioLine("CALLER", "Yeh TRAI se ek important suchna hai. Aapka mobile number 2 ghante mein permanently block hone wala hai illegal activities ki wajah se.", "0:03", "IMPERSONATION", "hi"),
            ScenarioLine("CALLER", "Agar yeh galti se hua hai toh 1 dabayein aur hamare cyber crime officer se baat karein.", "0:14", "URGENCY_CREATION", "hi"),
            ScenarioLine("CALLER", "Namaste, main Cyber Crime Cell se Inspector Verma bol raha hoon. Aapke number se 47 fraud complaints aayi hain.", "0:22", "IMPERSONATION", "hi"),
            ScenarioLine("VICTIM", "Yeh kaise ho sakta hai? Maine kuch nahi kiya!", "0:28", "NORMAL", "hi"),
            ScenarioLine("CALLER", "FIR already darj ho chuki hai. Court order ke mutabik aapko verification process complete karna hoga warna arrest hoga.", "0:33", "LEGAL_THREAT", "hi"),
        ],
    ),
]


def get_scenario_by_id(scenario_id: str) -> Scenario | None:
    for s in SCENARIOS:
        if s.id == scenario_id:
            return s
    return None


def list_scenarios() -> list[dict]:
    return [s.to_dict() for s in SCENARIOS]
